# Generated by Django 4.1.3 on 2022-12-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.TextField()),
                ('horas', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
