# Generated by Django 4.1.4 on 2022-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ec4", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carreras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("nombre_corto", models.CharField(max_length=150)),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
    ]
